[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.22"
version_scheme = "semver"
tag_format = "v$version"
major_version_zero = true
update_changelog_on_bump = true
version_files = [
  "pubspec.yaml:^version",
]
